/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  common\MotionProfiles.h
 *  model: RELbotSimple (1)
 *  expmt: RELbotSimple (1)
 *  date:  April 9, 2025
 *  time:  10:50:26 AM
 *  user:  Vakgroep RaM
 *  from:  -
 *  build: 5.1.4.13773
 **********************************************************/

/* This file defines the functions necessary for motion profiles
   functions
*/
