/cam2image:
  ros__parameters:
    width: 1080
    height: 1920
    socket_ip: 172.20.112.1
    socket_port: 9999
    remote_mode: true
    show_camera: true
    remote_timeout: 60
    history: "keep_last"
    durability: "volatile"
    reliability: "reliable"
    depth: 1
