/cam2image:
  ros__parameters:
    width: 300
    height: 200
    socket_ip:  145.126.55.200
    socket_port: 9999
    remote_mode: false
    show_camera: true
    remote_timeout: 7
    history: "keep_last"
    durability: "volatile"
    reliability: "reliable"
    depth: 10
    rotate: true